import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
export const metadata: Metadata = {
  title: "Landing | Tooningo",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function LandingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
        <body style={inter.style} className={inter.className}>
      <Navbar /> 
      {children}
      <Footer />
    </body>
    </html>
  );
}
