import React from 'react'
import TranslateClient from "@/components/translate/index"

export const metadata = {
    title: 'Translate - Tooningo',
    description: 'Generated by create next app',
  }

const TranslatePage = () => {
  return (
    <TranslateClient/>
  )
}

export default TranslatePage