import Navbar from "@/components/navbar";
import Footer from "@/components/footer"
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tooningo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={inter.style}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
