import React from "react";
import "./globals.css";
import type { Metadata } from "next";
import LayoutClient from "@/components/LayoutClient";
export const metadata: Metadata = {
  title: "Root | Tooningo",
  description: "Generated by create next app",
};
export default function LandingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
